### PR TITLE
Handling of DBRefs updates

### PR DESCRIPTION
**Pull request by aakhmerov**
1. Added Methods to handle DBRefs updates in cached objects that are persisted in hash map. As well as unit test for the case 
2. added FongoDBCursor implementation to bypass NPE in Mongo.isMongosConnection() method. This is unclear case for me and is rarely reproduced. I don't even understand how. I've created pull request to mongo java driver https://github.com/mongodb/mongo-java-driver/pull/111, not sure that it will be accepted though as the case is really vague. 

Both fixes are ugly in my opinion, so any comments if refactoring has to be done are welcome

### CODE REVIEW

**Comment by hoffrocket** [comment]
10gen recommends against using DBRefs in most and I'm unfamiliar with the usage semantics.  Can you explain the change a bit more?

I think there's a easier way to fix the isMongosConnection NPE.  I'll add a fix for that.

**Comment by hoffrocket** [comment]
A test case which duplicates the isMongosConnection NPE would be helpful. If you don't have that, then an example stack trace is ok. Is it possible that you have multiple versions of mockito on your classpath? (fongo depends on 1.9.0)

**Comment by hoffrocket** [comment]
going to close this out for now. please open another ticket if this is still a problem

**Comment by lukiano** [comment]
Hey guys, I hope this project is useful for you to try to fix the bug (isMongosConnection NPE)

https://github.com/lukiano/fongomockito

**Comment by hoffrocket** [comment]
Thanks for the repo. I still don't understand why this was happening in some circumstances and not others.  I created a workaround for this particular case and pushed a fix. I've verified that your test project works with 1.1.1-SNAPSHOT

**Comment by hoffrocket** [comment]
blerg, there's another case where it fails when a cursor is returned.

**Comment by lukiano** [comment]
Thanks! I'll wait for 1.1.1 then!

**Pull request closed without merging**
