### PR TITLE
Make fongo port configurable

### PR DESCRIPTION
**Pull request by palmerabollo**
The port is now configurable using an alternative Fongo constructor.

### CODE REVIEW

**Comment by hoffrocket** [comment]
why do you need this?

**Comment by palmerabollo** [comment]
I am planning to use fongo as part of my integration tests, as a mongodb mock. I need it to run in a different port because the real mongodb is already running in 27017. This way I don't have to stop the real mongo and it is less likely to loss valuable data if you make a mistake.

Maybe I am missing something and the port is not really used by fongo?

**Comment by hoffrocket** [comment]
fongo shouldn't bind to any port.  if you're getting some sort of port conflict exception, paste in the trace and i'll take a look.

**Comment by palmerabollo** [comment]
You are right, it does not bind to any port. I close it, I'm sorry about it.

**Pull request closed without merging**
