### PR TITLE
 Issue #29 reproduce example

### PR DESCRIPTION
**Pull request by avarabyeu**

### CODE REVIEW

**Comment by hoffrocket** [comment]
thanks, I published a fix.  please test on 1.0.9-SNAPSHOT

**Comment by avarabyeu** [comment]
Fixed. Thank you! When do you plan to release 1.0.9? We are using Maven and it's pretty important for us to have fix released.

**Comment by hoffrocket** [comment]
just released to oss repo.

**Comment by avarabyeu** [comment]
Jon, HUGE thank you!

**Pull request closed without merging**
